# Plugins-------------
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# Verilog Support
plug "rafael049/kakoune-verilog"
# Smart tab
plug "andreyorst/smarttab.kak"
# prelude
plug "lexherbo2/prelude.kak"
# auto-pair
plug "alexherbo2/auto-pairs.kak"
# rainbow pair
plug 'jjk96/kakoune-rainbow'

# Options -----
set-option global autoreload yes
set-option global scrolloff 3,5
set-option global tabstop 4
set-option global indentwidth 4
#set-option global rainbow-enable yes

# Highlighters
add-highlighter global/number-lines number-lines -relative -hlcursor
add-highlighter global/show-matching show-matching


# Colorscheme
colorscheme palenight

# Mappings
map global normal <c-q> ':quit<ret>'
map global normal <c-a-q> ':quit<ret>'
map global normal <c-s> ':write<ret>'

map global normal 0 gi
map global normal a li


# kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
        lsp-enable-window
}
lsp-auto-hover-enable # enable hover
set global lsp_hover_anchor true
set global lsp_hover_max_lines 40
map global user -docstring 'Rename Symbol' r ':lsp-rename-prompt<ret>'

